# docker-compose.yml
version: "3.7"

services:
  db-redis:
    container_name: db-redis-release
    image: redis:alpine
    environment:
      - TZ=Asia/Seoul
    hostname: db-redis
    labels:
      - "name=db-redis"
      - "mode=standalone"
    ports:
      - 6666:6666
    command: redis-server --port 6666 --appendonly yes --replica-read-only no

  backend:
    container_name: backend-release
    build: ./backend
    environment:
      - TZ=Asia/Seoul
    ports:
      - 8888:8888
    restart: always
    volumes:
      - /home/ubuntu/files-release:/var/lib/rollwrite
  
  frontend:
    container_name: frontend-release
    build: .
    ports:
      - 3333:3333
    restart: always
    volumes:
      - /home/ubuntu/files-release:/app/build/rollwrite

