# jwt
jwt:
  secret:
    atk: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
    rtk: kKHeDadyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1im
  # unit is ms. && atk : 1 hour (3600000) && rtk : 15 * 24 * 60 * 60 * 1000 = 15days (1296000000)
  expiration:
    atk: 3600000 # 30초 (30000)
    rtk: 1296000000 # 5분 (300000)

# kakao Login
auth:
  kakao:
    redirect-uri: http://localhost:8081/api/auth/kakao/login
    rest-key: 88cb08e0de73021429ec359e909db650
    secret-key: ZsXLSZ8AecIwF1Kg9YTMnaTF2DdcYeB1
